### ISSUE TITLE
binder crash with latest SDC (joyent_20160218T011055Z)

### ISSUE THREAD

**Issue by sigxcpu76** [joyent/binder#1]
```
[2016-03-02T17:30:56.916Z]  WARN: binder/named.Server/15236 on c105e901-82ef-4a92-a2b4-799601c33b58: query handler threw an uncaughtException (from=udp/10.4.1.44:53475, qId=13311, qName="", qType=A)
    AssertionError: '' == true
        at domainToPath (/opt/smartdc/binder/lib/zk.js:22:16)
        at Object.resolveName (/opt/smartdc/binder/lib/zk.js:249:23)
        at resolve (/opt/smartdc/binder/lib/server.js:82:12)
        at Server.onQuery (/opt/smartdc/binder/lib/server.js:228:25)
        at Server.emit (events.js:110:17)
        at Socket.<anonymous> (/opt/smartdc/binder/node_modules/named/lib/server.js:318:30)
        at Socket.emit (events.js:110:17)
        at UDP.onMessage (dgram.js:472:8)
[2016-03-02T17:30:56.917Z] FATAL: binder/15236 on c105e901-82ef-4a92-a2b4-799601c33b58: uncaughtException (exiting error code 1)
    AssertionError: '' == true
        at domainToPath (/opt/smartdc/binder/lib/zk.js:22:16)
        at Object.resolveName (/opt/smartdc/binder/lib/zk.js:249:23)
        at resolve (/opt/smartdc/binder/lib/server.js:82:12)
        at Server.onQuery (/opt/smartdc/binder/lib/server.js:228:25)
        at Server.emit (events.js:110:17)
        at Socket.<anonymous> (/opt/smartdc/binder/node_modules/named/lib/server.js:318:30)
        at Socket.emit (events.js:110:17)
        at UDP.onMessage (dgram.js:472:8)
```

**Comment by arekinath** [comment]
Thanks for reporting this -- this bug is MANTA-2856, and was already fixed by 2874adddd7d8fcec5705bfa7dc5dac8292189b49. This will be out in the next release very soon.
